[platformio]
boards_dir = ./board

[env:stable]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip

board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_speed = 115200

build_flags =  
    -std=gnu++17
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DLV_CONF_INCLUDE_SIMPLE  
    ;-DARDUINO_USB_MODE=1
    ;-DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -I src
    -I lib
    -I.pio/libdeps/stable
    -DCONFIG_SPIRAM_USE_MALLOC
    -UCONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL
    -DCONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384

lib_deps = 
    lvgl/lvgl @ 9.4.0
    lovyan03/LovyanGFX @ 1.2.19
    wollewald/MPU9250_WE @ 1.2.17 
    RobTillaart/BH1750FVI_RT @ 0.3.3
    esp32async/AsyncTCP @ 3.4.10
    https://github.com/marvinroger/async-mqtt-client.git#3d93fc7f662e65366f8e2b0d88b108f874f035b9